Sling update to 47
apache/sling-org-apache-sling-featureflags pull request #1
Opened 2022-05-19 12:00 UTC by ashokmca07

2022-05-24 14:18 UTC, rombert requested changes

2022-05-24 14:18 UTC, rombert commented on pom.xml
> -                            osgi.implementation;filter:="(&amp;(osgi.implementation=osgi.http)(version&gt;=1.0)(!(version&gt;=2.0)))"
The manifest of the new bundle does not have require this capability anymore. Was this intentional?

```
 ADDED      HEADER     Require-Capability:osgi.extender;filter:="(&(osgi.extender=osgi.component)(version>=1.3.0)(!(version>=2.0.0)))",osgi.implementation;filter:="(&(osgi.implementation=osgi.http)(version>=1.0)(!(version>=2.0)))",osgi.service;filter:="(objectClass=org.apache.sling.featureflags.Feature)";effective:=active;resolution:=optional;cardinality:=multiple,osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
 REMOVED    HEADER     Require-Capability:osgi.service;filter:="(objectClass=org.apache.sling.featureflags.Feature)";effective:=active;resolution:=optional;cardinality:=multiple,osgi.extender;filter:="(&(osgi.extender=osgi.component)(version>=1.4.0)(!(version>=2.0.0)))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

2022-05-26 20:47 UTC, apelluru commented on pom.xml
> -                            osgi.implementation;filter:="(&amp;(osgi.implementation=osgi.http)(version&gt;=1.0)(!(version&gt;=2.0)))"
In my tests, the bundle was working fine without this capability. but I have added like previous

2022-05-31 13:33 UTC, rombert approved these changes

2022-05-31 13:33 UTC, merged